/* EDIT INVITATION DETAILS HERE. No build or install required.
 * Keep English (en) and Urdu (ur) in sync.
 * eventTimes: four time strings; copy.*.times: matching event names.
 * contacts: two display numbers; copy.*.contactLabels: their labels.
 * guests: six [English surname, Urdu surname] pairs in portrait order.
 * Date: edit dateNumber, day, month and fullDate in BOTH languages.
 * Address: edit plusCode, copy.*.addressLine1/2 and mapUrl together.
 */
window.InvitationContent = {
  mapUrl:
    "https://www.google.com/maps/search/?api=1&query=Iqbal%20Marquee%206F2H%2B64X%20Water%20Works%20Road%20Qila%20Kuhna%20Qasim%20Bagh%20Multan",
contacts: [
  "Ajaz Ansari +92 3197831338",
  "Dr. Abdullah Muhammad +92 322 6646764",
],  eventTimes: ["7:00", "8:00", "9:00", "10:00"],
  guests: [
    ["Ahmed", "احمد"],
    ["Khan", "خان"],
    ["Ansari", "انصاری"],
    ["Malik", "ملک"],
    ["Siddiqui", "صدیقی"],
    ["Sheikh", "شیخ"],
  ],
  copy: {
    en: {
      invitation: "A WEDDING INVITATION",
      special: "Something beautiful is beginning",
      hamna: "Hamna Ansari",
      ali: "Ali Sufian",
      and: "weds",
      open: "Tap the seal to open",
      together: "Together with our families",
      invite: "With grateful hearts, we invite you to celebrate the Barat of",
      celebrate: "A celebration of love",
      scroll: "A little love awaits below",
      dateTitle: "A date close to our hearts",
      scratch: "Gently scratch the heart to uncover our special day",
      reveal: "Or tap to reveal",
      day: "Saturday",
      month: "September 2026",
      save: "Save the date",
      evening: "An evening to remember",
      schedule: "THE CELEBRATION",
      times: ["Refreshments", "Barat arrival", "Dinner", "Ruksati"],
      venue: "The place we’ll celebrate",
      venueName: "Iqbal Marquee",
      map: "Get directions",
      rsvp: "We look forward to celebrating with you",
      contact: "RSVP · Contact to follow",
      footer: "Your presence will make our day complete.",
      close: "Close invitation",
      revealed: "Our special day, revealed",
      scratchSurprise: "a little surprise",
      dateNumber: "26",
      fullDate: "Saturday, 26 September 2026",
      guestsEyebrow: "WITH THOSE WE LOVE",
      guestsTitle: "Our Cherished Guests",
      photoPlaceholder: "Photo to follow",
      contactHeading: "RSVP · Bride’s family",
      closingNames: "Hamna & Ali",
      addressLine1: "6F2H+64X Water Works Road,",
      addressLine2: "Qila Kuhna Qasim Bagh, Multan",
      contactLabels: ["Family contact 1", "Family contact 2"],
      couplePrefix: "Mr. & Mrs. ",
      eventNotes: [
        "A warm welcome",
        "The celebration begins",
        "Together at the table",
        "With love & blessings",
      ],
    },
    ur: {
      invitation: "دعوتِ بارات",
      special: "ایک خوبصورت سفر کا آغاز",
      hamna: "حمنہ انصاری",
      ali: "علی سفیان",
      and: "ہمراہ",
      open: "دعوت نامہ کھولنے کے لیے مہر کو چھوئیں",
      together: "اپنے اہلِ خانہ کے ہمراہ",
      invite:
        "ہم آپ کو خوشی کے اس مبارک موقع پر بارات کی تقریب میں شرکت کی دعوت دیتے ہیں",
      celebrate: "محبت کا ایک حسین جشن",
      scroll: "نیچے ایک خوبصورت لمحہ آپ کا منتظر ہے",
      dateTitle: "ہمارے دل کے قریب ایک تاریخ",
      scratch: "ہماری خاص تاریخ جاننے کے لیے دل پر آہستہ سے انگلی پھیریں",
      reveal: "یا تاریخ دیکھنے کے لیے یہاں چھوئیں",
      day: "ہفتہ",
      month: "ستمبر ۲۰۲۶",
      save: "یہ تاریخ یاد رکھیے",
      evening: "ایک یادگار شام",
      schedule: "تقریب کا پروگرام",
      times: ["تواضع", "آمدِ بارات", "کھانا", "رخصتی"],
      venue: "ہماری خوشیوں کا مقام",
      venueName: "اقبال مارکی",
      map: "مقام دیکھیے",
      rsvp: "آپ کی آمد ہمارے لیے باعثِ مسرت ہوگی",
      contact: "رابطہ نمبر جلد فراہم کیا جائے گا",
      footer: "آپ کی شرکت ہماری خوشیوں کو مکمل کرے گی۔",
      close: "دعوت نامہ بند کریں",
      revealed: "ہماری خاص تاریخ",
      scratchSurprise: "ایک چھوٹا سا راز",
      dateNumber: "۲۶",
      fullDate: "۲۶ ستمبر ۲۰۲۶، ہفتہ",
      guestsEyebrow: "ہمارے اپنے",
      guestsTitle: "ہمارے عزیز مہمان",
      photoPlaceholder: "تصویر جلد شامل ہوگی",
      contactHeading: "رابطہ — اہلِ خانۂ دلہن",
      closingNames: "حمنہ اور علی",
      addressLine1: "، واٹر ورکس روڈ،",
      addressLine2: "قلعہ کہنہ قاسم باغ، ملتان",
      contactLabels: ["رابطہ ۱", "رابطہ ۲"],
      couplePrefix: "جناب و بیگم ",
      eventNotes: [
        "خوش آمدید",
        "خوشیوں کی آمد",
        "مل بیٹھنے کا وقت",
        "دعاؤں کے سائے میں",
      ],
    },
  },
  plusCode: "6F2H+64X",
  sealInitials: ["A", "H"],
  bismillah: "بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ",
};
